spring:
  application:
    name: domain-security
  r2dbc:
    url: r2dbcs:mysql://47.96.110.3:3306/domain_security?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: Pfg85191558!
    pool:
      enabled: true
      initial-size: 10
      max-size: 100
      validation-query: 'SELECT 1'
